name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies, build your code if needed

      - name: Display EC2 host
        

      - name: Display EC2 username

      # Do not display the private key!
      # It's highly sensitive and should never be exposed in the logs

      - name: Copy code to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "."  # Source directory or files to copy
          target: "/home/ubuntu/"  # Destination directory on EC2

      # Add any additional steps like running deployment scripts on EC2
